version: '3.8'
services:
  app:
    image: nadyr19/springserver
    container_name: spring
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: nadyr19/mysqlserver
    container_name: mysql_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""  # Si vous laissez vide, a ssurez-vous de mettre une chaîne vide
      MYSQL_DATABASE: app
      MYSQL_USER: nadyr
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
